Frontend:
  impl: SimpleO3
  clock_ratio: 8
  num_expected_insts: 500000
  traces:
    - example_inst.trace

Translation:
  impl: RandomTranslation
  max_addr: 2147483648

MemorySystem:
  impl: GenericDRAM
  clock_ratio: 1

  DRAM:
    impl: HBM2
    org:
      preset: HBM2_4Gb
      channel: 1
      
    timing:
      preset: HBM2_2Gbps

  Controller:
    impl: Generic
    Scheduler:
      impl: FRFCFS
    RefreshManager:
      impl: AllBank
    RowPolicy:
      impl: ClosedRowPolicy
      cap: 4
    plugins: []

  AddrMapper:
    impl: RoBaRaCoCh
